#!/bin/sh

function copy()
{
	cp -f ../../build/gallery-$1 ../../../../jafl.github-yui3/$1;
}

function copy_js()
{
	cp -f ../../build/gallery-$1/gallery-$1-debug.js \
		  ../../../../jafl.github-yui3/$1/;
}

function copy_css()
{
	cp -f ../../build/gallery-$1/assets/skins/sam/gallery-$1.css \
		  ../../../../jafl.github-yui3/$1/assets/;

	cp -f ../../build/gallery-$1/assets/skins/sam/*.gif \
		  ../../../../jafl.github-yui3/$1/assets/;

	cp -f ../../build/gallery-$1/assets/skins/sam/*.png \
		  ../../../../jafl.github-yui3/$1/assets/;
}

copy_js accordion-horiz-vert;
copy accordion-horiz-vert/assets/gallery-accordion-horiz-vert-core.css;
cp -f ../../build/gallery-dimensions/gallery-dimensions-debug.js \
	  ../../../../jafl.github-yui3/accordion-horiz-vert/;

copy_js algorithms;

copy_js anim-class;
cp -f ../../build/gallery-funcprog/gallery-funcprog-debug.js \
	  ../../../../jafl.github-yui3/anim-class/;
cp -f ../../build/gallery-object-extras/gallery-object-extras-debug.js \
	  ../../../../jafl.github-yui3/anim-class/;

copy_js  bulkedit;
copy_css bulkedit;
cp -f ../../build/gallery-node-optimizations/gallery-node-optimizations-debug.js \
	  ../../../../jafl.github-yui3/bulkedit/;
cp -f ../../build/gallery-paginator/gallery-paginator-debug.js \
	  ../../../../jafl.github-yui3/bulkedit/;
cp -f ../../../../jafl.github-yui3/paginator/assets/* \
	  ../../../../jafl.github-yui3/bulkedit/assets/;
cp -f ../../build/gallery-formmgr-css-validation/gallery-formmgr-css-validation-debug.js \
	  ../../../../jafl.github-yui3/bulkedit/;
cp -f ../../build/gallery-checkboxgroups/gallery-checkboxgroups-debug.js \
	  ../../../../jafl.github-yui3/bulkedit/;
cp -f ../../build/gallery-busyoverlay/gallery-busyoverlay-debug.js \
	  ../../../../jafl.github-yui3/bulkedit/;
cp -f ../../../../jafl.github-yui3/busyoverlay/assets/* \
	  ../../../../jafl.github-yui3/bulkedit/assets/;
cp -f ../../build/gallery-object-extras/gallery-object-extras-debug.js \
	  ../../../../jafl.github-yui3/bulkedit/;
cp -f ../../build/gallery-nodelist-extras2/gallery-nodelist-extras2-debug.js \
	  ../../../../jafl.github-yui3/bulkedit/;

copy_js  busyoverlay;
copy_css busyoverlay;

copy_js canvas;

copy_js checkboxgroups;

copy_js complexnumber;
cp -f ../../build/gallery-math/gallery-math-debug.js \
	  ../../../../jafl.github-yui3/complexnumber/;
cp -f ../../build/gallery-test-extras/gallery-test-extras-debug.js \
	  ../../../../jafl.github-yui3/complexnumber/;
cp -f ../../build/gallery-console-test/gallery-console-test-debug.js \
	  ../../../../jafl.github-yui3/complexnumber/;
cp -f ../../build/gallery-console-test/assets/skins/sam/gallery-console-test.css \
	  ../../../../jafl.github-yui3/complexnumber/assets/;

copy_js expiration-cache;
cp -f ../../build/gallery-instancemanager/gallery-instancemanager-debug.js \
	  ../../../../jafl.github-yui3/expiration-cache/;
cp -f ../../build/gallery-test-extras/gallery-test-extras-debug.js \
	  ../../../../jafl.github-yui3/expiration-cache/;

copy_js  exprbuilder;
copy_css exprbuilder;
cp -f ../../build/gallery-querybuilder/gallery-querybuilder-debug.js \
	  ../../../../jafl.github-yui3/exprbuilder/;
cp -f ../../../../jafl.github-yui3/querybuilder/assets/* \
	  ../../../../jafl.github-yui3/exprbuilder/assets/;
cp -f ../../build/gallery-node-optimizations/gallery-node-optimizations-debug.js \
	  ../../../../jafl.github-yui3/exprbuilder/;
cp -f ../../build/gallery-formmgr-css-validation/gallery-formmgr-css-validation-debug.js \
	  ../../../../jafl.github-yui3/exprbuilder/;
cp -f ../../build/gallery-formmgr/gallery-formmgr-debug.js \
	  ../../../../jafl.github-yui3/exprbuilder/;

copy_js formmgr;
cp -f ../../build/gallery-formmgr-css-validation/gallery-formmgr-css-validation-debug.js \
	  ../../../../jafl.github-yui3/formmgr/;
cp -f ../../build/gallery-node-optimizations/gallery-node-optimizations-debug.js \
	  ../../../../jafl.github-yui3/formmgr/;

copy_js formmgr-overlay-plugin
cp -f ../../build/gallery-node-optimizations/gallery-node-optimizations-debug.js \
	  ../../../../jafl.github-yui3/formmgr-overlay-plugin/;
cp -f ../../build/gallery-formmgr-css-validation/gallery-formmgr-css-validation-debug.js \
	  ../../../../jafl.github-yui3/formmgr-overlay-plugin/;
cp -f ../../build/gallery-formmgr/gallery-formmgr-debug.js \
	  ../../../../jafl.github-yui3/formmgr-overlay-plugin/;

copy_js funcprog;
cp -f ../../build/gallery-object-extras/gallery-object-extras-debug.js \
	  ../../../../jafl.github-yui3/funcprog/;
cp -f ../../build/gallery-nodelist-extras2/gallery-nodelist-extras2-debug.js \
	  ../../../../jafl.github-yui3/funcprog/;

copy_js instancemanager;

copy_js io-multiresponse;

copy_js layout;
copy_css layout;
cp -f ../../build/gallery-layout-rows/gallery-layout-rows-debug.js \
	  ../../../../jafl.github-yui3/layout/;
cp -f ../../build/gallery-layout-cols/gallery-layout-cols-debug.js \
	  ../../../../jafl.github-yui3/layout/;
cp -f ../../build/gallery-dimensions/gallery-dimensions-debug.js \
	  ../../../../jafl.github-yui3/layout/;
cp -f ../../build/gallery-node-optimizations/gallery-node-optimizations-debug.js \
	  ../../../../jafl.github-yui3/layout/;
cp -f ../../build/gallery-funcprog/gallery-funcprog-debug.js \
	  ../../../../jafl.github-yui3/layout/;
cp -f ../../build/gallery-object-extras/gallery-object-extras-debug.js \
	  ../../../../jafl.github-yui3/layout/;
cp -f ../../build/gallery-paginator/gallery-paginator-debug.js \
	  ../../../../jafl.github-yui3/layout/;
cp -f ../../../../jafl.github-yui3/paginator/assets/* \
	  ../../../../jafl.github-yui3/layout/assets/;

copy_js linkedlist;
cp -f ../../build/gallery-iterable-extras/gallery-iterable-extras-debug.js \
	  ../../../../jafl.github-yui3/linkedlist/;
cp -f ../../build/gallery-test-extras/gallery-test-extras-debug.js \
	  ../../../../jafl.github-yui3/linkedlist/;
cp -f ../../build/gallery-funcprog/gallery-funcprog-debug.js \
	  ../../../../jafl.github-yui3/linkedlist/;
cp -f ../../build/gallery-object-extras/gallery-object-extras-debug.js \
	  ../../../../jafl.github-yui3/linkedlist/;

copy_js math;
cp -f ../../build/gallery-test-extras/gallery-test-extras-debug.js \
	  ../../../../jafl.github-yui3/math/;

copy_js  mathcanvas;
copy_css mathcanvas;
cp -f ../../build/gallery-math/gallery-math-debug.js \
	  ../../../../jafl.github-yui3/mathcanvas/;
cp -f ../../build/gallery-complexnumber/gallery-complexnumber-debug.js \
	  ../../../../jafl.github-yui3/mathcanvas/;
cp -f ../../build/gallery-canvas/gallery-canvas-debug.js \
	  ../../../../jafl.github-yui3/mathcanvas/;
cp -f ../../build/gallery-node-optimizations/gallery-node-optimizations-debug.js \
	  ../../../../jafl.github-yui3/mathcanvas/;

copy_js multiobject;
cp -f ../../build/gallery-paginator/gallery-paginator-debug.js \
	  ../../../../jafl.github-yui3/multiobject/;
cp -f ../../../../jafl.github-yui3/paginator/assets/* \
	  ../../../../jafl.github-yui3/multiobject/assets/;

copy_js neon;

copy_js dimensions;

copy_js node-optimizations;

copy_js scrollintoview;
cp -f ../../build/gallery-dimensions/gallery-dimensions-debug.js \
	  ../../../../jafl.github-yui3/scrollintoview/;

copy_js nodelist-extras2;

copy_js object-extras;

copy_js  paginator;
copy_css paginator;

copy_js  querybuilder;
copy_css querybuilder;
cp -f ../../build/gallery-node-optimizations/gallery-node-optimizations-debug.js \
	  ../../../../jafl.github-yui3/querybuilder/;
cp -f ../../build/gallery-formmgr-css-validation/gallery-formmgr-css-validation-debug.js \
	  ../../../../jafl.github-yui3/querybuilder/;
cp -f ../../build/gallery-formmgr/gallery-formmgr-debug.js \
	  ../../../../jafl.github-yui3/querybuilder/;
cp -f ../../build/gallery-paginator/gallery-paginator-debug.js \
	  ../../../../jafl.github-yui3/querybuilder/;
cp -f ../../../../jafl.github-yui3/paginator/assets/* \
	  ../../../../jafl.github-yui3/querybuilder/assets/;

copy_js  quickedit;
copy_css quickedit;
cp -f ../../build/gallery-paginator/gallery-paginator-debug.js \
	  ../../../../jafl.github-yui3/quickedit/;
cp -f ../../../../jafl.github-yui3/paginator/assets/* \
	  ../../../../jafl.github-yui3/quickedit/assets/;
cp -f ../../build/gallery-formmgr-css-validation/gallery-formmgr-css-validation-debug.js \
	  ../../../../jafl.github-yui3/quickedit/;
cp -f ../../build/gallery-node-optimizations/gallery-node-optimizations-debug.js \
	  ../../../../jafl.github-yui3/quickedit/;
cp -f ../../build/gallery-funcprog/gallery-funcprog-debug.js \
	  ../../../../jafl.github-yui3/quickedit/;
cp -f ../../build/gallery-object-extras/gallery-object-extras-debug.js \
	  ../../../../jafl.github-yui3/quickedit/;

copy_js  treeble;
copy_css treeble;
cp -f ../../build/gallery-paginator/gallery-paginator-debug.js \
	  ../../../../jafl.github-yui3/treeble/;
cp -f ../../../../jafl.github-yui3/paginator/assets/* \
	  ../../../../jafl.github-yui3/treeble/assets/;
