#!/bin/sh

function copy()
{
	cp -f ../../build/gallery-$1 ../../../../jafl.github-yui3/$1;
}

function copy_js()
{
	cp -f ../../build/gallery-$1/gallery-$1-debug.js \
	      ../../../../jafl.github-yui3/$1/;
}

function copy_css()
{
	cp -f ../../build/gallery-$1/assets/skins/sam/gallery-$1.css \
	      ../../../../jafl.github-yui3/$1/assets/;

	cp -f ../../build/gallery-$1/assets/skins/sam/*.gif \
	      ../../../../jafl.github-yui3/$1/assets/;

	cp -f ../../build/gallery-$1/assets/skins/sam/*.png \
	      ../../../../jafl.github-yui3/$1/assets/;
}

copy_js accordion-horiz-vert;
copy accordion-horiz-vert/assets/gallery-accordion-horiz-vert-core.css;

copy_js checkboxgroups;

copy_js io-multiresponse;

copy_js neon;

copy_js canvas;

copy_js formmgr;

copy_js  paginator;
copy_css paginator;

copy_js multiobject;
cp -f ../../build/gallery-paginator/gallery-paginator-debug.js \
      ../../../../jafl.github-yui3/multiobject/;
cp -f ../../../../jafl.github-yui3/paginator/assets/* \
      ../../../../jafl.github-yui3/multiobject/assets/;

copy_js  treeble;
copy_css treeble;
cp -f ../../build/gallery-paginator/gallery-paginator-debug.js \
      ../../../../jafl.github-yui3/treeble/;
cp -f ../../../../jafl.github-yui3/paginator/assets/* \
      ../../../../jafl.github-yui3/treeble/assets/;

copy_js  querybuilder;
copy_css querybuilder;
cp -f ../../build/gallery-formmgr/gallery-formmgr-debug.js \
      ../../../../jafl.github-yui3/querybuilder/;
cp -f ../../build/gallery-paginator/gallery-paginator-debug.js \
      ../../../../jafl.github-yui3/querybuilder/;
cp -f ../../../../jafl.github-yui3/paginator/assets/* \
      ../../../../jafl.github-yui3/querybuilder/assets/;

copy_js  exprbuilder;
copy_css exprbuilder;
cp -f ../../build/gallery-querybuilder/gallery-querybuilder-debug.js \
      ../../../../jafl.github-yui3/exprbuilder/;
cp -f ../../../../jafl.github-yui3/querybuilder/assets/* \
      ../../../../jafl.github-yui3/exprbuilder/assets/;
cp -f ../../build/gallery-formmgr/gallery-formmgr-debug.js \
      ../../../../jafl.github-yui3/exprbuilder/;

copy_js bulkedit;
cp -f ../../build/gallery-formmgr/gallery-formmgr-debug.js \
      ../../../../jafl.github-yui3/bulkeditor/;
cp -f ../../build/gallery-paginator/gallery-paginator-debug.js \
      ../../../../jafl.github-yui3/bulkeditor/;
cp -f ../../../../jafl.github-yui3/paginator/assets/* \
      ../../../../jafl.github-yui3/bulkeditor/assets/;

copy_js scrollintoview;
cp -f ../../build/gallery-dimensions/gallery-dimensions-debug.js \
      ../../../../jafl.github-yui3/scrollintoview/;
